services:
  api:
    container_name: backend
    hostname: backend
    build:
      context: backend/
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd123!!!"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
